image: tetraweb/php:7.0

variables:
  SIMPLETEST_DB: "sqlite://tmp/site.sqlite"
  SIMPLETEST_BASE_URL: "http://127.0.0.1:8080"
  COMPOSER_EXIT_ON_PATCH_FAILURE: "1"

before_script:
    - docker-php-ext-enable zip date dom filter gd hash json pcre pdo session SimpleXML SPL tokenizer xml

build:
  stage: build
  script:
    #- echo 'max_execution_time = 120' >> drupal.php.ini
    # - echo 'sendmail_path = /bin/true' >> drupal.php.ini
    # - phpenv config-add drupal.php.ini
    # - phpenv rehash
    # - phpenv config-rm xdebug.ini
    - composer --verbose install
    - ls
    - cd web
    - ./../vendor/bin/drush site-install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite
    - cd ..
    - sh scripts/ahs/deploy.sh
    - cd web
    - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
    - sleep 3

  
#    services:
#    - tetraweb/mysql


#script:
#  - cd $TRAVIS_BUILD_DIR
#  - vendor/bin/behat --profile travis    
#    
#deploy:
#  artifacts:
#    paths:
#    - build/
## only:
#    - dev
#  script:
#    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
#    - ssh -p22 server_user@server_host "mkdir htdocs/wp-content/themes/_tmp"
#    - scp -P22 -r build/* server_user@server_host:htdocs/wp-content/themes/_tmp
#    - ssh -p22 server_user@server_host "mv htdocs/wp-content/themes/live htdocs/wp-content/themes/_old && mv htdocs/wp-content/themes/_tmp htdocs/wp-content/themes/live"
#    - ssh -p22 server_user@server_host "rm -rf htdocs/wp-content/themes/_old"