language: php
php:
  - 7.0

sudo: false

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - composer --verbose install

before_script:
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install minimal --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../vendor/bin/drush config-set "system.site" uuid "2748a6a9-0c67-43c6-aa47-71df4737a69f" --yes
  - for module in `cat ../modules.common`; do ./../vendor/bin/drush --yes pm-enable $module; done
  - for module in `cat ../modules.dev`; do ./../vendor/bin/drush --yes pm-enable $module; done
  - ./../vendor/bin/drush --yes config-import --skip-modules="$(echo $(cat ../modules.master) | tr " " "," )"
  - for module in `cat ../modules.dev`; do ./../vendor/bin/drush --yes pm-uninstall $module; done
  - for module in `cat ../modules.master`; do ./../vendor/bin/drush --yes pm-enable $module; done
  - ./../vendor/bin/drush runserver http://127.0.0.1:8080 &
  - sleep 3

script:
  - cd $TRAVIS_BUILD_DIR
  - vendor/bin/behat --profile travis
notifications:
  email: false
